{% set version = "2.5" %}
{% set date = "2014-03-27" %}

{% set variant = "openblas" %}

package:
  name: python-spams
  version: {{ version }}

source:
  fn: spams-{{ version }}.tar.gz
  url: http://spams-devel.gforge.inria.fr/hitcounter2.php?file=33816/spams-python-v{{ version }}-svn{{ date }}.tar.gz
  sha1: f6f6d7fe385773690f886ee6d077a1cdf6f2ba41

  patches:
    # Fix how BLAS is detected. Mailed to developer.
    - setup.py.patch
    # Update bindings for NumPy 1.10.x from 1.9.x.
    - spams_wrap.cpp.patch
    - spams_wrap-windows.cpp.patch

build:
  skip: true  # [win or py3k]
  number: 204
  detect_binary_files_with_prefix: true
  features:
    - blas_{{ variant }}

requirements:
  build:
    - gcc
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - numpy x.x
    - scipy
    # For tests.
    - pillow
    
  run:
    - libgcc
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - numpy x.x
    - scipy

test:
  imports:
    - spams

about:
  home: http://spams-devel.gforge.inria.fr/
  license: GPL 3
  summary: An optimization toolbox for solving various sparse estimation problems.

extra:
  recipe-maintainers:
    - jakirkham
