{% set version = "2.6.1" %}
{% set date = "2017-12-08" %}
{% set file_num = "37237" %}

{% set variant = "openblas" %}

package:
  name: python-spams
  version: {{ version }}

source:
  fn: spams-python-{{ version }}.tar.gz
  url: http://spams-devel.gforge.inria.fr/hitcounter2.php?file={{ file_num }}/spams-python-v{{ version }}-svn{{ date }}.tar.gz
  sha256: 3012529c0461bd777228dce53c880f2a5fa2aaf22b5d673a1f22045a63f4d8bc

  patches:
    # patch setup.py to link to LLVM's OpenMP library instead of GCC's.
    - llvm_openmp_setup.py.patch  # [osx]
    # array creation requires integers for shape specification.
    - spams.py.patch

build:
  skip: true  # [win or (osx and cxx_compiler == "toolchain_cxx")]
  number: 1202
  detect_binary_files_with_prefix: true
  features:
    - blas_{{ variant }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - llvm-openmp                    # [osx]
  host:
    - python
    - pip
    - blas 1.1 {{ variant }}
    - openblas
    - llvm-openmp                    # [osx]
    - numpy
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas
    - llvm-openmp                    # [osx]
    - {{ pin_compatible('numpy') }}
    - scipy
    - six

test:
  source_files:
    # Test data
    - extdata/boat.png
    - extdata/lena.png
    # Test suite
    - test_decomp.py
    - test_dictLearn.py
    - test_linalg.py
    - test_prox.py
    - test_spams.py
    - test_utils.py
  requires:
    - pillow
  imports:
    - spams

about:
  home: http://spams-devel.gforge.inria.fr/
  license: GPL 3
  license_family: GPL
  license_file: LICENSE.txt
  summary: An optimization toolbox for solving various sparse estimation problems.

extra:
  recipe-maintainers:
    - jakirkham
    - zym1010
