{% set version = "2.6.5.4" %}



package:
  name: python-spams
  version: {{ version }}

source:
  fn: spams-python-{{ version }}.tar.gz
  url: https://github.com/getspams/spams-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 67efbd1a23a2afb087df5b24267e9a5dbfa9ff44e7a01de5900aec2d54f4a97c

  patches:
    # patch setup.py to link to LLVM's OpenMP library instead of GCC's.
    - llvm_openmp_setup.py.patch  # [osx]
    # array creation requires integers for shape specification.
    - spams.py.patch

build:
  skip: true  # [win or (osx and cxx_compiler == "toolchain_cxx")]
  number: 1204
  detect_binary_files_with_prefix: true
  features:

requirements:
  build:
    - {{ compiler("cxx") }}
    - llvm-openmp      
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]              # [osx]
  host:
    - libblas
    - liblapack
    - python
    - pip
    - llvm-openmp                    # [osx]
    - numpy
  run:
    - python
    - llvm-openmp                    # [osx]
    - {{ pin_compatible('numpy') }}
    - scipy
    - six

test:
  source_files:
    # Test data
    - extdata/boat.png
    - extdata/lena.png
    # Test suite
    - test_decomp.py
    - test_dictLearn.py
    - test_linalg.py
    - test_prox.py
    - test_spams.py
    - test_utils.py
  requires:
    - pillow
  imports:
    - spams

about:
  home: http://spams-devel.gforge.inria.fr/
  license: GPL 3
  license_family: GPL
  license_file: LICENSE.txt
  summary: An optimization toolbox for solving various sparse estimation problems.

extra:
  recipe-maintainers:
    - zym1010
