appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {osx: circle}
travis:
  secure: {BINSTAR_TOKEN: xf9MdfnGnsZGxEGL9A6nU/lVohhmw6WDKj2eiNGceyGnNrtVZxQY3bmS8+9hLE5IKAUC7dy4KRd9HdHq97uBMwYNxacKIoQUwuIi5CtKysRQ1ojY3OFSaCzavM/SBRfMceIyVJ9Wyv5HkhYvj19ckAUtcYcT8cK8izQCLA5I18JK6CtJNSfSCOamLHHHRAcwCOwC6Gy42+DdCJLSjxvp4fHYfibNr9BrtiBVeefX+Ynpq/g8zAmpFe3u5c2Pd0pVhCKzMzz2NetKmc1VFYaxDVv1mkTgApAz7QEy2tEfx6G8KKKcYL4Bne8VH4Rjt8kOnHg45bzKjW0TGba2T5eulQ5yNftb3afHcw86JtTQQDwy9PBKTIrH1E7UWv4QgZLmxUrKPZoIAKQVDCuha40pMsC29p4cFq20R2OxGiZPa4CWzDXwBbV+8jFjD7UHuy4ODaAFNvQj4LgHTSf+PwHGe1mf1HQLRe9KUQXrcXD9TKkbQ+ezyPZ4E9LLgapazg5HMrhaGQHXFGtPr4iDsvVyJYt8kJGkJXQ38ZDZAncopehegKQSgfODLIvGNPGdbZASmQpuBfwkvZlGoTrNMV0c8CgqywE4xxdHCuvzL2m3e5hgvvI8goyI/XIO1lyb7xufNe6QWw2HgB4GnOYnhizl8b71Oky5ODP+Mwfxq5uDsPM=}
